Automatically select oci-ta tasks if appropriate
If the pipeline looks like a trusted artifact pipeline, and if the
task specified has a matching "-oci-ta" version, automatically use
that "-oci-ta" version of the task.

This simplifiles the "one-liner" instructions since users no longer
have to figure out which of the two versions to use. The script will
decide automatically if it needs to use the trusted-artifact version
of a task.

diff --git a/pipeline-patcher b/pipeline-patcher
--- a/pipeline-patcher
+++ b/pipeline-patcher
@@ -109,6 +109,18 @@ list_known_tasks() {
     echo "$_known_tasks_memo"
 }
 
+task_exists() {
+    local task_name=$1
+
+    list_known_tasks | grep -qE "^$task_name "
+}
+
+oci_ta_task_exists() {
+    local task_name=$1
+
+    task_exists "$task_name-oci-ta"
+}
+
 # Put together a yaml snippet with a bundle resolved taskRef ready to insert
 # into a Konflux pipeline
 extract_pipeline_task() {
@@ -197,33 +209,47 @@ insert_pipeline_task() {
     local new_task_name="$2"
     local before_task_name="$3"
 
-    if detect_task_in_pipeline $pipeline_file $new_task_name; then
-        echo "Task '$new_task_name' found already in pipeline '$(basename $pipeline_file)'. Skipping."
+    # Make sure the task is a known task
+    if ! task_exists $new_task_name; then
+        echo "Can't find pipeline task '$new_task_name'. Skipping."
         return
     fi
 
+    if detect_oci_ta_pipeline $pipeline_file; then
+        # Pipeline is using trusted artifact tasks
+        if [[ ! $new_task_name =~ -oci-ta$ ]]; then
+            # Check if there is a -oci-ta version of the task
+            if oci_ta_task_exists $new_task_name; then
+                # Use the -oci-ta task if it exists
+                new_task_name="$new_task_name-oci-ta"
+            fi
+        fi
+    else
+        # Pipeline is not using trusted artifact tasks
+        if [[ $new_task_name =~ -oci-ta$ ]]; then
+            # Bail out if a trusted artifact task was requested
+            # (This is unusual so let's not switch tasks automatically.)
+            echo "Adding an oci-ta task to a non-oci-ta pipeline is probably a mistake. Skipping."
+            return
+        fi
+    fi
+
+    # Make sure the "before" task is present
     if ! detect_task_in_pipeline $pipeline_file $before_task_name; then
         echo "Before task '$before_task_name' not found in pipeline '$(basename $pipeline_file)'. Skipping."
         return
     fi
 
-    if ! detect_oci_ta_pipeline $pipeline_file; then
-        if [[ $new_task_name =~ -oci-ta$ ]]; then
-            echo "Adding an oci-ta task to a non-oci-ta pipeline is probably a mistake. Skipping."
-            return
-        fi
-    else
-        if [[ ! $new_task_name =~ -oci-ta$ ]]; then
-            echo "Looks like your pipeline is oci-ta. Consider if there's an oci-ta version of this task you should use instead."
-            # But continue, since it might be fine. Not all tasks in an oci-ta pipeline use the trusted artifacts.
-            # Todo maybe: See if there is a related -oci-ta task and if there is just use it automatically
-        fi
+    # Make sure we don't add it twice
+    if detect_task_in_pipeline $pipeline_file $new_task_name; then
+        echo "Task '$new_task_name' found already in pipeline '$(basename $pipeline_file)'. Skipping."
+        return
     fi
 
     echo "Adding task $new_task_name to pipeline $pipeline_file"
 
     # The tasks have a name in the taskRef resolver and a name in the pipeline. Since
-    # those can be different we now going to find the pipeline name of the "before task",
+    # those can be different we're now going to find the pipeline name of the "before" task,
     # i.e. the task that we want to use to determine the place to insert the task.
     local before_task_pipeline_name=$(find_task_in_pipeline $pipeline_file $before_task_name | yq '.name')
 
